


management:
 health:
   circuitbreakers:
      enabled: true
 endpoints:
    web:
      exposure:
        include: health
 endpoint:
    health:
      show-details: always     
        
resilience4j:
 circuitbreaker:
   instances: 
    custfallback:
     registerHealthIndicator: true
     eventConsumerBufferSize: 10
     failureRateThreshold: 50
     minimumNumberOfCalls: 5
     automaticTransitionFromOpenToHalfOpenEnabled: true
     waitDurationInOpenState: 20
     permittedNumberOfCallsInHalfOpenState: 3
     slidingWindowSize: 10
     slidingWindowType: COUNT_BASED
   
 
